# Generated by GitHub Copilot
"""Test suite validating the Hugging Face Llama support added to LatentMAS.

These tests are intentionally lightweight: they use a tiny randomly
initialized ``LlamaForCausalLM`` (a few MB) and never load the real
Llama-3.2-3B weights, so they run on CPU within a constrained environment.

Run with:
    python -m unittest test_llama_support -v
"""

import argparse
import importlib.util
import os
import sys
import types
import unittest
from unittest import mock

import torch

# Ensure the LatentMAS package root is importable when invoked directly.
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
if _THIS_DIR not in sys.path:
    sys.path.insert(0, _THIS_DIR)

import models  # noqa: E402
from models import ModelWrapper, _past_length, _mean_embedding_norm  # noqa: E402

from transformers import LlamaConfig, LlamaForCausalLM  # noqa: E402


def _tiny_llama(tie_word_embeddings: bool = True) -> LlamaForCausalLM:
    """Build a tiny CPU LlamaForCausalLM for fast, low-memory testing."""
    config = LlamaConfig(
        vocab_size=64,
        hidden_size=32,
        intermediate_size=64,
        num_hidden_layers=2,
        num_attention_heads=4,
        num_key_value_heads=2,
        max_position_embeddings=128,
        tie_word_embeddings=tie_word_embeddings,
    )
    model = LlamaForCausalLM(config)
    model.eval()
    return model


def _realign_args(enabled: bool, chunk_size: int = 4096, reg: float = 1e-5):
    """Create an argparse.Namespace carrying realignment configuration."""
    return argparse.Namespace(
        latent_space_realign=enabled,
        realign_chunk_size=chunk_size,
        realign_regularization=reg,
    )


def _bare_wrapper(model, args):
    """Construct a ModelWrapper without running its heavy __init__."""
    wrapper = ModelWrapper.__new__(ModelWrapper)
    wrapper.model = model
    wrapper.device = torch.device("cpu")
    wrapper.args = args
    wrapper._latent_realign_matrices = {}
    wrapper.pre_aligned = None
    wrapper.model_type = model.config.model_type
    return wrapper


class FakeTokenizer:
    """Minimal tokenizer stub: decode returns space-joined token ids."""

    pad_token_id = 0

    def decode(self, ids, skip_special_tokens=True):
        return " ".join(str(int(i)) for i in ids)


class TestPastLength(unittest.TestCase):
    """Item 16.1 / 16.2: _past_length supports modern and legacy caches."""

    def test_dynamic_cache(self):
        model = _tiny_llama()
        ids = torch.randint(0, 64, (1, 5))
        with torch.no_grad():
            out = model(input_ids=ids, use_cache=True, return_dict=True)
        # Modern transformers returns a Cache/DynamicCache object here.
        self.assertTrue(hasattr(out.past_key_values, "get_seq_length"))
        self.assertEqual(_past_length(out.past_key_values), 5)

    def test_legacy_tuple_cache(self):
        # Legacy tuple-of-tuples cache: [layers][k/v] -> [B, H, seq, D].
        legacy = ((torch.zeros(1, 2, 7, 8), torch.zeros(1, 2, 7, 8)),)
        self.assertEqual(_past_length(legacy), 7)

    def test_none_cache(self):
        self.assertEqual(_past_length(None), 0)


class TestLatentCacheReuse(unittest.TestCase):
    """Items 16.3-16.6: cache reuse + one-token inputs_embeds latent pass."""

    def test_input_ids_then_latent_embed_grows_cache_by_one(self):
        model = _tiny_llama()
        ids = torch.randint(0, 64, (1, 6))

        with torch.no_grad():
            out1 = model(
                input_ids=ids,
                use_cache=True,
                output_hidden_states=True,
                return_dict=True,
            )
        past = out1.past_key_values
        len1 = _past_length(past)
        self.assertEqual(len1, 6)

        latent_embed = out1.hidden_states[-1][:, -1:, :]
        self.assertEqual(
            tuple(latent_embed.shape), (1, 1, model.config.hidden_size)
        )

        with torch.no_grad():
            out2 = model(
                inputs_embeds=latent_embed,
                past_key_values=past,
                use_cache=True,
                output_hidden_states=True,
                return_dict=True,
            )
        len2 = _past_length(out2.past_key_values)
        self.assertEqual(len2, len1 + 1)


class TestRealignMatrix(unittest.TestCase):
    """Items 16.7-16.13: realignment matrix behavior."""

    def test_disabled_returns_identity_without_solve(self):
        model = _tiny_llama()
        wrapper = _bare_wrapper(model, _realign_args(enabled=False))
        hidden_size = model.config.hidden_size

        with mock.patch.object(
            torch.linalg, "solve", wraps=torch.linalg.solve
        ) as solve_spy:
            matrix, target_norm = wrapper._build_latent_realign_matrix(
                model, torch.device("cpu"), wrapper.args
            )

        self.assertEqual(solve_spy.call_count, 0)
        self.assertTrue(
            torch.allclose(matrix, torch.eye(hidden_size), atol=1e-6)
        )
        self.assertGreater(float(target_norm), 0.0)

    def test_enabled_calls_solve_and_returns_square_matrix(self):
        model = _tiny_llama(tie_word_embeddings=False)
        wrapper = _bare_wrapper(model, _realign_args(enabled=True))
        hidden_size = model.config.hidden_size

        with mock.patch.object(
            torch.linalg, "solve", wraps=torch.linalg.solve
        ) as solve_spy:
            matrix, _ = wrapper._build_latent_realign_matrix(
                model, torch.device("cpu"), wrapper.args
            )

        self.assertGreaterEqual(solve_spy.call_count, 1)
        self.assertEqual(tuple(matrix.shape), (hidden_size, hidden_size))
        self.assertTrue(torch.isfinite(matrix).all())

    def test_tied_weights_not_skipped(self):
        model = _tiny_llama(tie_word_embeddings=True)
        # Confirm weights actually share storage.
        in_w = model.get_input_embeddings().weight
        out_w = model.get_output_embeddings().weight
        self.assertEqual(in_w.data_ptr(), out_w.data_ptr())

        wrapper = _bare_wrapper(model, _realign_args(enabled=True))
        hidden_size = model.config.hidden_size

        with mock.patch.object(
            torch.linalg, "solve", wraps=torch.linalg.solve
        ) as solve_spy:
            matrix, _ = wrapper._build_latent_realign_matrix(
                model, torch.device("cpu"), wrapper.args
            )

        # Even when tied, generation must NOT be skipped.
        self.assertGreaterEqual(solve_spy.call_count, 1)
        self.assertEqual(tuple(matrix.shape), (hidden_size, hidden_size))

    def test_chunked_matches_full_computation(self):
        model = _tiny_llama(tie_word_embeddings=False)
        reg = 1e-5
        # Force several chunks (vocab_size=64) to exercise chunked accumulation.
        wrapper = _bare_wrapper(
            model, _realign_args(enabled=True, chunk_size=8, reg=reg)
        )
        hidden_size = model.config.hidden_size

        chunked, _ = wrapper._build_latent_realign_matrix(
            model, torch.device("cpu"), wrapper.args
        )

        ein = model.get_input_embeddings().weight.detach().float()
        wout = model.get_output_embeddings().weight.detach().float()
        gram_full = wout.T @ wout
        rhs_full = wout.T @ ein
        full = torch.linalg.solve(
            gram_full + reg * torch.eye(hidden_size), rhs_full
        )

        self.assertTrue(torch.allclose(chunked, full, atol=1e-4, rtol=1e-4))

    def test_mean_embedding_norm_chunked_matches_direct(self):
        weight = torch.randn(40, 16)
        chunked = _mean_embedding_norm(weight, chunk_size=7)
        direct = torch.linalg.vector_norm(weight.float(), dim=1).mean()
        self.assertTrue(torch.allclose(chunked, direct, atol=1e-5))


class TestQwenStylePreserved(unittest.TestCase):
    """Item 16.16: generic (Qwen-compatible) behavior remains intact."""

    def test_untied_model_realign_and_identity_paths(self):
        model = _tiny_llama(tie_word_embeddings=False)

        # Disabled -> identity, no solve (matches prior generic behavior).
        wrapper_off = _bare_wrapper(model, _realign_args(enabled=False))
        matrix_off, _ = wrapper_off._build_latent_realign_matrix(
            model, torch.device("cpu"), wrapper_off.args
        )
        self.assertTrue(
            torch.allclose(
                matrix_off, torch.eye(model.config.hidden_size), atol=1e-6
            )
        )

        # Legacy tuple cache still supported (Qwen relied on this path).
        legacy = ((torch.zeros(1, 2, 3, 8), torch.zeros(1, 2, 3, 8)),)
        self.assertEqual(_past_length(legacy), 3)


class TestImportWithoutVLLM(unittest.TestCase):
    """Item 16.14: HF path imports successfully without vLLM installed."""

    def test_vllm_absent(self):
        self.assertIsNone(
            importlib.util.find_spec("vllm"),
            "vLLM should be absent for this test to be meaningful.",
        )
        # models.py must import and report no vLLM.
        self.assertFalse(models._HAS_VLLM)
        # methods.latent_mas must import with SamplingParams set to None.
        import methods.latent_mas as lm

        self.assertIsNone(lm.SamplingParams)


class TestLeftPaddedDecode(unittest.TestCase):
    """Item 16.15: left-padded batched decoding returns generated tokens only."""

    def test_only_generated_tokens_returned(self):
        # Fake model whose generate() appends known new tokens to input_ids.
        new_tokens = torch.tensor([[101, 102, 103], [201, 202, 203]])

        class FakeGenModel:
            def generate(self, input_ids, attention_mask, **kw):
                seqs = torch.cat([input_ids, new_tokens], dim=-1)
                return types.SimpleNamespace(
                    sequences=seqs, past_key_values=None
                )

        wrapper = ModelWrapper.__new__(ModelWrapper)
        wrapper.model = FakeGenModel()
        wrapper.tokenizer = FakeTokenizer()
        wrapper.device = torch.device("cpu")

        # Left-padded batch: row 0 has a leading pad (0); row 1 is full.
        input_ids = torch.tensor([[0, 5, 6], [7, 8, 9]])
        attention_mask = torch.tensor([[0, 1, 1], [1, 1, 1]])

        texts, _ = wrapper.generate_text_batch(
            input_ids,
            attention_mask,
            max_new_tokens=3,
        )

        # Decoded text must contain ONLY the generated tokens, not the prompt.
        self.assertEqual(texts[0], "101 102 103")
        self.assertEqual(texts[1], "201 202 203")


if __name__ == "__main__":
    unittest.main(verbosity=2)
